### ISSUE TITLE
Updating to latest swagger-node-runner

### ISSUE THREAD

**Issue by ngoctranfire** [apigee-127/swagger-express#8]
Hey, when will this be updated to be using the latest swagger-node-runner?

**Comment by theganyo** [comment]
Hi,
If you install the latest version of this, it should automatically pick up the latest swagger-node-runner. 
Scott

**Comment by ngoctranfire** [comment]
Okay I see. Thanks!

**Comment by dlbrown06** [comment]
```
Error initializing middleware
TypeError: swaggerExpress.runner.on is not a function
```
Doesn't appear to pick it up

**Comment by theganyo** [comment]
Did you run `npm update`?

**Comment by dlbrown06** [comment]
Yeah. I did the following:
```
npm install --save swagger-node-runner
npm update
```

Then included the following into my file and I'm still getting this error posted above.
```
swaggerExpress.runner.on('responseValidationError', function(validationResponse, request, response) {
    // log your validationResponse here...
    console.error(validationResponse.errors);
});
```

**Comment by theganyo** [comment]
Try running:  `npm ls swagger-node-runner`

You should see something like this:

swagger-express-mw@0.7.0 /Users/sganyo/dev/swagger-express
└── swagger-node-runner@0.7.2

**Comment by dlbrown06** [comment]
Here is what I get:
```
├─┬ swagger-express-mw@0.1.0
│ └── swagger-node-runner@0.5.13 
└── swagger-node-runner@0.7.2 
```

**Comment by dlbrown06** [comment]
Argh!

I updated the version of `swagger-express-mw`... looks to be working now...

Thanks!

**Comment by theganyo** [comment]
Great!
